export const {
  REST_APP_PORT,
  JWT_SECRET_KEY,
  POSTGRES_DB,
  POSTGRES_USERNAME,
  POSTGRES_PASSWORD,
  POSTGRES_HOST,
  REDIS_HOST,
  NODE_ENV,
  TASK_GRPC_APP_HOST,
  TASK_GRPC_APP_PORT,
} = process.env as Record<string, string>;
